name: 名称：构建 EXE  # 这里可以写中文，显示在网页标题上

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: 结账代码
        uses: actions/checkout@v3

      - name: 设置 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: 安装依赖项
        run: npm install

      - name: 安装软件包
        run: npm install -g pkg

      - name: 生成EXE
        run: pkg .  # 确保 package.json 中已配置 bin 或 main 字段

      - name: 上传工件
        uses: actions/upload-artifact@v4  # 【关键修正】升级为 v4
        with:
          name: 可执行文件
          path: '*.exe'
